title: 'Features'
listing:
  - id: 'modularity'
    title: 'Modularity is the keyword for a lot of possibilities'
    type: 'list'
    content:
      - 'Use the standalone guide'
      - 'Use a popular guide'
      - 'Create&Pimp your custom guide by selecting the desired modules, maybe saving it for later use'
  - id: 'modules'
    title: 'Browse&Use existing modules (guide fragments) or write your own'
