title: 'Guide Builder'

standalone:
  title: 'Standalone'
  subtitle:
    'The standalone guide is the classic one, containing all of the basic modules, featuring a complete setup.'

popular:
  title: 'Popular'
  subtitle: 'The popular guides are those created by the community'

custom:
  title: 'Custom'
  subtitle:
    'Here you can create your custom guide by selecting the desired modules'
