title: 'Awesome Gentoo Setup'
acronym: 'Awesootup'
desc: 'Modular gentoo setup guides'
motto: 'The modular gentoo setup guides that work!'
license:
  name: 'GPLv3'
  website: 'http://www.gnu.org/licenses/gpl-3.0.html'
